[package]
name = "smiscvm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
colorize = "0.1.0"
crossterm = "0.29.0"
ctrlc = "3.4.7"
include_dir = "0.7.4"
rand = "0.9.0"
termimad = "0.33.0"
